### ISSUE TITLE
Dokan Quantity Discount Features Improvement

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2019]
### Is your feature request related to a problem? Please describe.

- [x] 1. Woo Mini Cart: The Woo Mini Cart displays the subtotal of the order which exclude the Dokan Quantity Discount so users do not see the real price including the Dokan Quantity Discount as the Dokan Quantity Discount is calculated after the sub total. If there is a quantity discount, the user should see the total of the order including the Dokan Qty Discount and excluding shipping cost instead of the sub-total order. For now he needs to go to the cart / checkout page to really know the price and seeing the full amount of an order. Without seeing the accurate price including the discount can be discouraging and push the user not to proceed further: https://github.com/getdokan/dokan/issues/2120

- [x] 2. Dokan Quantity Discount calculation should adapt to the Woocommerce structure of the website meaning Dokan Quantity Discount should be calculated including taxes if the marketplace adds and shows price including taxes. It should reflect the correct discount amount and make sure customers are not getting confused by this option. 

Note that woocommerce has only 2 options, either add and show everything inclusive of taxes or add and show everything excluding taxes. Mixing these settings is not supported by Woocommerce: https://ibb.co/wdsLQ3T 
For now your Dokan Quantity Discount option works well only for websites that add and show their price excluding taxes. But not when we are adding and showing price inclusive of taxes.

Example: Prices are added to the website including taxes. So for a product which costs 70 euros and has the discount of "Buy 2 and get 50% off", the total order for 2 products should be 70 euros including taxes (and excluding shipping cost). But for some reason, instead of having a discount of 70 euros, once the user buys 2 products, he/she gets a discount of 57.85 euros. Please review this video: https://share.vidyard.com/watch/ZJTmvBVkPdrbHj5W6wGVCs?

- [x] 3. Products which have the Dokan discount option are not considered such as Woocommerce "On Sale" products as they don't have a discounted price so if we want to show the "On Sale" products in a product loop, we only see the products which have the default woocommerce discounted price but not the products which have the Dokan Quantity Discount option, while they are on sale too thanks to the Quantity discount. Please review detailed issue here: https://github.com/getdokan/dokan/issues/2118

Products which have this Dokan Quantity discount should be associated to Woocommerce On Sale products so they are also display in the On Sale Woocommerce Product Loops.

- [x] 4. Finally, the Discount Amount is not reported in the same way between the customer cart/checkout/global order, the sub order and the seller order so it is very confusing as it gives 3 different numbers, dedicated GitHub issue here: https://github.com/getdokan/dokan/issues/2231

### Describe the solution you'd like

Check explanation above

### Describe alternatives you've considered

Check explanation above

**Comment by Aunshon** [comment]
@Sophie-2e hi.
Could you please the number 3 again ? the video is not working.

**Comment by Sophie-2e** [comment]
Hello @Aunshon, yes I shot this video last year and unfortunately I don't have it anymore. But basically Product with a Dokan Quantity Discount are not considered as "On Sale"/'Discounted" product by Woocommerce so they are not shown in "On Sale/Discounted" Product Loop. I believe that since, it is working for simple product now, but product with variation still do not work. Please let me know if that clear. And here is the dedicated GitHub opened for it: https://github.com/getdokan/dokan/issues/2118

**Comment by Sophie-2e** [comment]
@Aunshon @imtiaz-pranto => Other issue related to Dokan Quantity Discount and added in the summary of this GIT HUB issue: https://github.com/getdokan/dokan/issues/2231
